name: Pylint

on:

  # Allow manual triggers
  workflow_dispatch:

  # Run only on pushes to the main branch (direct or via merge)
  push:
    branches:
      - main

  # Trigger on PR creation or updates targeting any branch
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r ./st_ui/requirements.txt
        pip install -r ./utils/requirements.txt
        pip install -r ./tools/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
