name: Pytest Tests and Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r ./st_ui/requirements.txt
        pip install -r ./utils/requirements.txt

    - name: Run tests with pytest and coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest --cov=./ --cov-report=xml --cov-report=term-missing --cov-fail-under=10

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true