name: ST UI Build Test Deploy

on:
  # Manual run
  workflow_dispatch:

  # Tigger on unit test completion
  workflow_run:
    workflows:
      - Pytest
    types:
      - completed

# Need permissions to publish
permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    name: Build Docker Image
    runs-on: ubuntu-latest

    # Check success if this was tiggered by another workflow run
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    outputs:
      image_name: ${{ steps.build-image.outputs.image_name }}
      image_tag: ${{ steps.build-image.outputs.image_tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      id: build-image
      run: |

        # Exit on failure
        set -e

        IMAGE_NAME=$(echo "ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/st_ui" | tr '[:upper:]' '[:lower:]')

        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG=pr-${{ github.event.pull_request.number }}-${{ github.run_id }}
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG=latest
        else
            TAG=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        fi

        # Build the image
        docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

        # Save to environment variables
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

        # Save to job output
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Pre Push Smoke Test
      run: |

        # Exit on failure
        set -e
        # Run it
        docker run -d --name streamlit-test -p 8501:8501 $IMAGE_NAME:${IMAGE_TAG:-latest}

        # Poll every 1 second for 30 seconds
        for i in {1..30}; do
            RESPONSE=$(curl -s http://localhost:8501 || true)
            if echo "$RESPONSE" | grep -q "You need to enable JavaScript to run this app"; then
                echo "App started successfully."
                break
            fi
            echo "Waiting for app to start... ($i/30)"
            sleep 1
        done

        # Verify if the app responded correctly
        if ! echo "$RESPONSE" | grep -q "You need to enable JavaScript to run this app"; then
            echo "App failed to start within 30 seconds."
            exit 1
        fi

    - name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Cleanup
      if: always()
      run: |
        docker stop streamlit-test
        docker rm streamlit-test

  post-push-smoke-test:
    name: Post-Push Smoke Test
    runs-on: ubuntu-latest
    needs: build-test-push

    steps:
    - name: Pull Docker Image
      env:
        IMAGE_NAME: ${{ needs.build-test-push.image_name }}
        IMAGE_TAG: ${{ needs.build-test-push.outputs.image_tag }}
      run: |
        docker pull $IMAGE_NAME:$IMAGE_TAG

    - name: Cleanup
      if: always()
      run: |
        docker stop streamlit-test
        docker rm streamlit-test
